# Generated by Django 3.1.4 on 2021-03-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
    ]
